### ISSUE TITLE
"Invalid scheme in uri" error while trying to connect using narmal mongo url 'mongodb+srv://[username]:[password]@[host]'

### ISSUE THREAD

**Issue by Omar-IDOUDAOUD** [mongo-dart/mongo_db_driver#2]
`await mongoClient.connect();`

**Comment by giorgiofran** [comment]
Can you give an example of the url that you are using?

**Comment by Omar-IDOUDAOUD** [comment]
> Can you give an example of the url that you are using?
Thank for answering, iam using a normal mongo database url: mongodb+srv://myusename:mypassword@cluster0.ytc4tjd.mongodb.net/

**Comment by Omar-IDOUDAOUD** [comment]
@giorgiofran 
Thank you for answering, iam using a normal mongo database url: mongodb+srv://myusename:mypassword@cluster0.ytc4tjd.mongodb.net/
` var client = MongoClient("mongodb+srv://myusename:mypassword@cluster0.ytc4tjd.mongodb.net/");
  await client.connect();`

**Comment by giorgiofran** [comment]
Thanks, I will check this in the next days.

**Comment by Omar-IDOUDAOUD** [comment]
Thank you so much for fixing the issue; it's working now!
