### ISSUE TITLE
Where is `ObjectId`?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_db_driver#5]
I am trying to use this package instead of the [`mongo_dart`](https://pub.dev/packages/mongo_dart)  package.
But I don't see the `ObjectId` object from the `mongo_dart` package. (change name?)

Can I use these packages together if some function/object isn't contained in this package?
Are there any cautions?

**Comment by giorgiofran** [comment]
Import the package Bson to use the ObjectId class. 

``` dart
import 'package:bson/bson.dart';
```
